apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: 923975749308.dkr.ecr.ap-northeast-1.amazonaws.com/cart-service:1.0.1S
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    app: cart-service
  annotations:
#Important Note:  Need to add health check path annotations in service level if we are planning to use multiple targets in a load balancer    
    alb.ingress.kubernetes.io/healthcheck-path: /cart
spec:

  selector:
    app: cart-service
  ports:
    - port: 8080
      targetPort: 8080

 
