apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cart-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    alb.ingress.kubernetes.io/scheme: internet-facing  
    alb.ingress.kubernetes.io/target-type: ip 
    alb.ingress.kubernetes.io/load-balancer-name: ingress-groups-demo
    alb.ingress.kubernetes.io/group.name: myapps.web
    alb.ingress.kubernetes.io/group.order: '20'

spec:
  ingressClassName: my-aws-ingress-class   # Ingress Class                       
  rules:
    - http:
        paths:           
          - path: /cart
            pathType: Prefix
            backend:
              service:
                name: cart-service
                port: 
                  number: 8080
          # - path: /stage
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: payment-service
          #       port:
          #         number: 8080 
          # - path: /gatway
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: payment-service
          #       port:
          #         number: 8080                 
                       
             

# [k8s_nodes]
# k8s-worker1 ansible_host=192.168.75.118 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ubuntu/.ssh/Tokyo.pem ansible_ssh_common_args='-o ProxyJump=bastion'
# k8s-worker2 ansible_host=192.168.115.186 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ubuntu/.ssh/Tokyo.pem ansible_ssh_common_args='-o ProxyJump=bastion'




# [jenkins_slaves]
# slave1-dev ansible_host=172.31.32.26 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/Tokyo.pem
# slave2-stage ansible_host=172.31.46.2 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/Tokyo.pem
# slave3-prod ansible_host=172.31.42.219 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/Tokyo.pem
