apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-ingress-2
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    alb.ingress.kubernetes.io/load-balancer-name: project-lb-2
spec:
  rules:
  - host: project-lb-395642569.ap-northeast-1.elb.amazonaws.com
    http:
      paths:
        - path: /cart
          backend:
            service:
              name: cart-service
              port:
                number: 8080
        