apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-ingress-3
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    alb.ingress.kubernetes.io/load-balancer-name: project-lb-3
spec:
  rules:
  - http:
      paths:
        - path: /gatway
          backend:
            serviceName: gatway-service
            servicePort: 8080
        