apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-ingress-2
  annotations:
    # Load Balancer Name
    alb.ingress.kubernetes.io/load-balancer-name: project-lb
    ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: my-aws-ingress-class   # Ingress Class                       
  rules:
    - http:
        paths:           
          - path: /gatway
            pathType: Prefix
            backend:
              service:
                name: gatway-service
                port: 
                  number: 8080
                       
             

        